/**
 * The hand-off from the pipeline to the database, end to end.
 *
 * This is the seam the whole product turned on. The pipeline assembled a
 * WorldDocument and uploaded it as a file; nothing ever wrote wv_room,
 * wv_camera, wv_entity or any of the rest; so wv-view and wv-export served a
 * world with no rooms in it. These tests are what says that is closed, and
 * they are written against the SAME world the Python suite builds --
 * spatial/pipeline/tests/data/handoff_fixture.json, generated by the pipeline
 * and checked for drift by tests/test_handoff.py. Testing the round trip
 * against a document invented here would prove that this file agrees with
 * itself.
 *
 * The property being proved is not "rows appear". It is that a document can go
 * in and come back out saying the same thing -- which is what makes it safe to
 * treat the database as the world and the document as a rendering of it.
 */

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { handleJobs } from '../../../../../supabase/functions/wv-jobs/handler.ts';
import {
  buildWorldDocument, markWorldDocumentStale, readWorldDocument,
  DOCUMENT_CHUNK_KEY, RAW_DOCUMENT_OBJECT_NAME,
} from '../../../../../supabase/functions/_wv_shared/worldDocument.ts';
import { worldObjectIds } from '../../../../../supabase/functions/_wv_shared/worldIngest.ts';
import {
  compareWorldDocuments, summariseDifferences,
} from '../../../../../supabase/functions/_wv_shared/worldDiff.ts';
import { FakeDb, FakeStorage, makeDeps, req } from './edgeHarness.js';

interface Fixture {
  worldId: string;
  propertyId: string;
  version: number;
  label: string;
  assets: Record<string, unknown>[];
  document: Record<string, unknown>;
  sections: Record<string, unknown>[];
}

const FIXTURE: Fixture = JSON.parse(readFileSync(fileURLToPath(
  new URL('../../../../pipeline/tests/data/handoff_fixture.json', import.meta.url),
), 'utf8')) as Fixture;

const WORLD_A = FIXTURE.worldId;
const PROP_A = FIXTURE.propertyId;
const ORG_A = '11111111-1111-4111-8111-111111111111';
const ORG_B = '22222222-2222-4222-8222-222222222222';
const PROP_B = '44444444-4444-4444-8444-444444444444';
const WORLD_B = '66666666-6666-4666-8666-666666666666';
const WORKER = 'cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const JOB = 'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';
const SECRET = 'a'.repeat(48);
const ASSET_BUCKET = 'wv-assets';

const utf8 = (s: string): Uint8Array => new TextEncoder().encode(s);

/**
 * Two tenants, one leased job. Every isolation assertion below crosses that
 * boundary deliberately; a single-tenant fixture cannot test isolation at all.
 */
function ingestDb(): FakeDb {
  const db = new FakeDb({
    strictColumns: ['wv_world', 'wv_room', 'wv_entity', 'wv_asset', 'wv_property'],
  });
  db.seed('wv_org', [{ id: ORG_A, slug: 'alpha', name: 'Alpha Lettings' },
    { id: ORG_B, slug: 'beta', name: 'Beta Estates' }]);
  db.seed('wv_property', [
    { id: PROP_A, org_id: ORG_A, label: FIXTURE.label },
    { id: PROP_B, org_id: ORG_B, label: 'Beta House' },
  ]);
  db.seed('wv_world', [
    {
      id: WORLD_A, property_id: PROP_A, version: FIXTURE.version, status: 'processing',
      published_at: null, quality_score: null, slug: 'flat-2-alpha-court',
      created_at: '2026-09-19T09:00:00.000Z',
    },
    {
      id: WORLD_B, property_id: PROP_B, version: 1, status: 'draft',
      published_at: null, quality_score: null, slug: 'beta-house',
      created_at: '2026-09-19T09:00:00.000Z',
    },
  ]);
  db.seed('wv_worker', [{ id: WORKER, name: 'gpu-01', capabilities: [] }]);
  db.seed('wv_job', [{
    id: JOB, world_id: WORLD_A, stage: 'quality', status: 'leased',
    worker_id: WORKER, attempt: 1, depends_on: [],
  }]);
  db.setRpc('wv_org_of_world', (args) => (
    String(args['p_world']) === WORLD_A ? ORG_A
      : String(args['p_world']) === WORLD_B ? ORG_B : null));
  return db;
}

function rig() {
  const db = ingestDb();
  const storage = new FakeStorage();
  // The build artefact the commit diffs the rows against. The worker uploads
  // it before the hand-off starts, under a name nobody will mistake for the
  // world.
  storage.put(ASSET_BUCKET, `${WORLD_A}/${RAW_DOCUMENT_OBJECT_NAME}`,
    utf8(JSON.stringify(FIXTURE.document)));
  const base = makeDeps({ db, storage, env: { WV_WORKER_SECRET: SECRET } });
  return { db, storage, deps: base.deps, logs: base.logs };
}

function send(deps: unknown, body: Record<string, unknown>) {
  return handleJobs(req({
    headers: { 'x-wv-worker-secret': SECRET },
    body: { action: 'ingest-world', jobId: JOB, workerId: WORKER, ...body },
  }), deps as never);
}

/** Every section the pipeline emits, in the order it emits them. */
async function handOff(deps: unknown, over: Record<string, unknown> = {}) {
  const out: { section: string; status: number; body: unknown }[] = [];
  for (const body of FIXTURE.sections) {
    const res = await send(deps, { ...body, ...over });
    out.push({ section: String(body['section']), status: res.status, body: res.body });
  }
  return out;
}

const sectionBody = (name: string): Record<string, unknown> =>
  ({ ...FIXTURE.sections.find((s) => s['section'] === name)! });

function counts(doc: Record<string, unknown>) {
  const nav = doc['nav'] as { nodes: unknown[]; edges: unknown[] };
  return {
    floors: (doc['floors'] as unknown[]).length,
    rooms: (doc['rooms'] as unknown[]).length,
    surfaces: (doc['surfaces'] as unknown[]).length,
    openings: (doc['openings'] as unknown[]).length,
    cameras: (doc['cameras'] as unknown[]).length,
    entities: (doc['entities'] as unknown[]).length,
    navNodes: nav.nodes.length,
    navEdges: nav.edges.length,
    regions: (doc['regions'] as unknown[]).length,
    relationships: (doc['relationships'] as unknown[]).length,
  };
}

// ---------------------------------------------------------------------------
// The round trip
// ---------------------------------------------------------------------------

describe('wv-jobs ingest-world', () => {
  it('writes the whole world and renders it back unchanged', async () => {
    const { db, deps, storage } = rig();
    const results = await handOff(deps);

    for (const r of results) {
      expect(r.status, `${r.section}: ${JSON.stringify(r.body)}`).toBe(200);
    }

    const expected = counts(FIXTURE.document);
    expect(db.rows('wv_floor')).toHaveLength(expected.floors);
    expect(db.rows('wv_room')).toHaveLength(expected.rooms);
    expect(db.rows('wv_surface')).toHaveLength(expected.surfaces);
    expect(db.rows('wv_opening')).toHaveLength(expected.openings);
    expect(db.rows('wv_camera')).toHaveLength(expected.cameras);
    expect(db.rows('wv_entity')).toHaveLength(expected.entities);
    expect(db.rows('wv_nav_node')).toHaveLength(expected.navNodes);
    expect(db.rows('wv_nav_edge')).toHaveLength(expected.navEdges);
    expect(db.rows('wv_region')).toHaveLength(expected.regions);
    expect(db.rows('wv_relationship')).toHaveLength(expected.relationships);

    // The assertion the whole design rests on: what comes back out is what
    // went in. The commit already made it -- a 200 means it found nothing --
    // but making it here too is what turns a failure into a readable one.
    const rendered = await buildWorldDocument(db, WORLD_A);
    const ids = await worldObjectIds(WORLD_A, FIXTURE.document);
    const diffs = compareWorldDocuments(FIXTURE.document, rendered, ids);
    expect(summariseDifferences(diffs)).toBe('no differences');

    // A world becomes viewable because it passed, not because a pipeline
    // finished, and the rendered document is written where readers find it.
    const world = db.rows('wv_world').find((w) => w['id'] === WORLD_A)!;
    expect(world['status']).toBe('published');
    expect(world['published_at']).toBeTruthy();
    const cached = db.rows('wv_asset').find((a) => a['chunk_key'] === DOCUMENT_CHUNK_KEY)!;
    expect(cached['world_id']).toBe(WORLD_A);
    expect(cached['storage_path']).toBe(`${WORLD_A}/world.json`);
    expect(storage.objects.has(`${ASSET_BUCKET}/${WORLD_A}/world.json`)).toBe(true);
  });

  it('never lists its own container among the world\'s assets', async () => {
    const { db, deps } = rig();
    await handOff(deps);
    const doc = await buildWorldDocument(db, WORLD_A);
    const keys = (doc['assets'] as { chunkKey?: string }[]).map((a) => a.chunkKey);
    expect(keys).not.toContain(DOCUMENT_CHUNK_KEY);
    expect(keys).not.toContain('world-raw');
    // The real assets are all still there.
    expect((doc['assets'] as unknown[]).length)
      .toBe((FIXTURE.document['assets'] as unknown[]).length);
  });

  it('records metric scale as estimated, never as reconstructed', async () => {
    const { db, deps } = rig();
    await handOff(deps);
    const doc = await buildWorldDocument(db, WORLD_A);
    const scale = doc['scale'] as { grounding: { provenance: string } };
    expect(scale.grounding.provenance).toBe('inferred');
    // And every area measured with that metre inherits it.
    const room = (doc['rooms'] as { area: { grounding: { provenance: string } } }[])[0]!;
    expect(room.area.grounding.provenance).toBe('inferred');
  });
});

// ---------------------------------------------------------------------------
// Resume
// ---------------------------------------------------------------------------

describe('a hand-off that has to be sent twice', () => {
  it('does not duplicate a single row', async () => {
    const { db, deps } = rig();
    await handOff(deps);
    const after = Object.fromEntries(
      ['wv_floor', 'wv_room', 'wv_surface', 'wv_opening', 'wv_camera', 'wv_entity',
        'wv_nav_node', 'wv_nav_edge', 'wv_region', 'wv_relationship', 'wv_asset',
        'wv_quality']
        .map((t) => [t, db.rows(t).length]));

    // The pod died, the lease was reclaimed, the job ran again from its
    // checkpoints and is sending the identical world a second time.
    const second = await handOff(deps);
    for (const r of second) expect(r.status, r.section).toBe(200);

    for (const [table, n] of Object.entries(after)) {
      expect(db.rows(table).length, `${table} grew on the second pass`).toBe(n);
    }
    const rendered = await buildWorldDocument(db, WORLD_A);
    const ids = await worldObjectIds(WORLD_A, FIXTURE.document);
    expect(summariseDifferences(compareWorldDocuments(FIXTURE.document, rendered, ids)))
      .toBe('no differences');
  });

  it('does not undo an operator\'s rename when it re-sends the same build', async () => {
    const { db, deps } = rig();
    await handOff(deps);
    const room = db.rows('wv_room')[0]!;
    await db.update('wv_room', { name: 'Front reception' }, { id: String(room['id']) });

    await send(deps, sectionBody('rooms'));

    // The build has no opinion about the room's name, so the section does not
    // carry one, so the upsert does not touch the column. A resumed ingest
    // that reverted corrections would make corrections worthless.
    expect(db.rows('wv_room').find((r) => r['id'] === room['id'])!['name'])
      .toBe('Front reception');
  });

  it('accepts a section\'s chunks in any order', async () => {
    const { db, deps } = rig();
    const cameraRows = sectionBody('cameras')['rows'] as unknown[];
    const half = Math.floor(cameraRows.length / 2);

    for (const body of FIXTURE.sections) {
      if (body['section'] !== 'cameras') {
        expect((await send(deps, body)).status, String(body['section'])).toBe(200);
        continue;
      }
      // Cameras, split in two and delivered back to front. Chunk order
      // carries no meaning: every row is keyed by its own content, so the
      // second half landing first is not a partial write to be repaired, it
      // is simply half the section.
      const second = await send(deps, {
        section: 'cameras', rows: cameraRows.slice(half), chunkIndex: 1, chunkCount: 2,
      });
      expect(second.status).toBe(200);
      expect(db.rows('wv_camera')).toHaveLength(cameraRows.length - half);
      const first = await send(deps, {
        section: 'cameras', rows: cameraRows.slice(0, half), chunkIndex: 0, chunkCount: 2,
      });
      expect(first.status).toBe(200);
    }

    expect(db.rows('wv_camera')).toHaveLength(cameraRows.length);
  });
});

// ---------------------------------------------------------------------------
// Ordering against the schema's foreign keys
// ---------------------------------------------------------------------------

describe('a section that arrives before the one it depends on', () => {
  it('is refused by name rather than as a foreign-key violation', async () => {
    const { db, deps } = rig();
    await send(deps, sectionBody('header'));

    const res = await send(deps, sectionBody('surfaces'));
    expect(res.status).toBe(422);
    const body = res.body as { error: string; detail: { needs: string[] } };
    expect(body.detail.needs).toContain('rooms');
    // Nothing was written: a half-ingested section would leave surfaces with
    // no room, which renders as a world whose walls belong to nothing.
    expect(db.rows('wv_surface')).toHaveLength(0);
  });

  it('is refused for a nav edge whose nodes have not landed', async () => {
    const { db, deps } = rig();
    for (const name of ['header', 'floors', 'rooms']) {
      expect((await send(deps, sectionBody(name))).status).toBe(200);
    }
    const res = await send(deps, sectionBody('nav-edges'));
    expect(res.status).toBe(422);
    expect((res.body as { detail: { needs: string[] } }).detail.needs).toContain('nav-nodes');
    expect(db.rows('wv_nav_edge')).toHaveLength(0);
  });

  it('is refused for an entity citing a camera that has not landed', async () => {
    const { db, deps } = rig();
    for (const name of ['header', 'floors', 'rooms']) {
      await send(deps, sectionBody(name));
    }
    const res = await send(deps, sectionBody('entities'));
    expect(res.status).toBe(422);
    expect((res.body as { detail: { needs: string[] } }).detail.needs).toContain('cameras');
    expect(db.rows('wv_entity')).toHaveLength(0);
  });

  it('succeeds once the section it needed has landed', async () => {
    const { db, deps } = rig();
    for (const name of ['header', 'floors', 'rooms']) await send(deps, sectionBody(name));
    expect((await send(deps, sectionBody('surfaces'))).status).toBe(200);
    expect(db.rows('wv_surface').length).toBeGreaterThan(0);
    expect(db.rows('wv_surface').every((s) => s['room_id'])).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// The comparison at commit
// ---------------------------------------------------------------------------

describe('the commit check', () => {
  it('catches a room that did not survive the write, and refuses to publish', async () => {
    const { db, deps, storage } = rig();
    for (const body of FIXTURE.sections) {
      if (body['section'] === 'commit') continue;
      await send(deps, body);
    }

    // One room's write was lost. Nothing else in the system would notice: the
    // job succeeded, the assets are there, the quality gate passed.
    const rooms = db.rows('wv_room');
    const dropped = rooms.shift()!;

    const res = await send(deps, { section: 'commit' });
    expect(res.status).toBe(422);
    const body = res.body as { error: string; summary: string; differences: { kind: string; section: string; key: string }[] };
    expect(body.error).toContain('does not match the world that was built');
    expect(body.differences.some((d) => d.kind === 'missing' && d.section === 'rooms')).toBe(true);
    expect(body.summary).toContain('missing rooms');

    // A world that does not match what was built does not go live, and no
    // document is cached for a reader to pick up.
    const world = db.rows('wv_world').find((w) => w['id'] === WORLD_A)!;
    expect(world['status']).not.toBe('published');
    expect(db.rows('wv_asset').some((a) => a['chunk_key'] === DOCUMENT_CHUNK_KEY)).toBe(false);
    expect(storage.objects.has(`${ASSET_BUCKET}/${WORLD_A}/world.json`)).toBe(false);
    expect(dropped['stable_key']).toBeTruthy();
  });

  it('is not tripped by row order, which carries no meaning', async () => {
    const { db, deps } = rig();
    for (const body of FIXTURE.sections) {
      if (body['section'] === 'commit') continue;
      await send(deps, body);
    }
    for (const table of ['wv_room', 'wv_surface', 'wv_camera', 'wv_entity',
      'wv_nav_node', 'wv_relationship', 'wv_region', 'wv_asset']) {
      db.rows(table).reverse();
    }
    expect((await send(deps, { section: 'commit' })).status).toBe(200);
  });

  it('refuses when there is no build artefact to check against', async () => {
    const { db, deps, storage } = rig();
    storage.objects.delete(`${ASSET_BUCKET}/${WORLD_A}/${RAW_DOCUMENT_OBJECT_NAME}`);
    for (const body of FIXTURE.sections) {
      if (body['section'] === 'commit') continue;
      await send(deps, body);
    }
    const res = await send(deps, { section: 'commit' });
    expect(res.status).toBe(422);
    expect((res.body as { error: string }).error).toContain('cannot be verified');
    expect(db.rows('wv_world').find((w) => w['id'] === WORLD_A)!['status'])
      .not.toBe('published');
  });

  it('catches a measurement that changed on the way in', async () => {
    const { db, deps } = rig();
    for (const body of FIXTURE.sections) {
      if (body['section'] === 'commit') continue;
      await send(deps, body);
    }
    const room = db.rows('wv_room')[0]!;
    room['area_m2'] = Number(room['area_m2']) + 1.5;
    const res = await send(deps, { section: 'commit' });
    expect(res.status).toBe(422);
    const diffs = (res.body as { differences: { field?: string }[] }).differences;
    expect(diffs.some((d) => d.field === 'area.value')).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// Tenancy
// ---------------------------------------------------------------------------

describe('an ingest aimed at another org\'s world', () => {
  it('writes into the leased job\'s world and nowhere else', async () => {
    const { db, deps } = rig();
    // A hostile or simply wrong worker naming org B's world in every way it
    // can. world_id comes from the job row; the body is never consulted.
    const results = await handOff(deps, {
      worldId: WORLD_B, world_id: WORLD_B, targetWorldId: WORLD_B,
    });
    for (const r of results) expect(r.status, r.section).toBe(200);

    for (const table of ['wv_floor', 'wv_room', 'wv_surface', 'wv_opening',
      'wv_camera', 'wv_entity', 'wv_nav_node', 'wv_nav_edge', 'wv_region',
      'wv_relationship', 'wv_asset', 'wv_quality']) {
      expect(db.rows(table).length, `${table} wrote nothing`).toBeGreaterThan(0);
      expect(db.rows(table).every((r) => r['world_id'] === WORLD_A),
        `${table} escaped into another tenant`).toBe(true);
    }
    // Org B's world is untouched, in every column that matters.
    const b = db.rows('wv_world').find((w) => w['id'] === WORLD_B)!;
    expect(b['status']).toBe('draft');
    expect(b['published_at']).toBeNull();
    expect(b['scale_source']).toBeUndefined();
  });

  it('refuses a worker that does not hold the lease', async () => {
    const { db, deps } = rig();
    const res = await handleJobs(req({
      headers: { 'x-wv-worker-secret': SECRET },
      body: {
        action: 'ingest-world', jobId: JOB,
        workerId: 'dddddddd-dddd-4ddd-8ddd-dddddddddddd',
        ...sectionBody('rooms'),
      },
    }), deps as never);
    expect(res.status).toBe(409);
    expect(db.rows('wv_room')).toHaveLength(0);
  });

  it('refuses without the shared secret, and never accepts an anon key', async () => {
    const { db, deps } = rig();
    const attempts: Record<string, string>[] = [
      {},
      { 'x-wv-worker-secret': 'wrong' },
      // The anon key is printed in every page of the site. It must buy nothing.
      { authorization: 'Bearer some.anon.key' },
    ];
    for (const headers of attempts) {
      const res = await handleJobs(req({
        headers,
        body: { action: 'ingest-world', jobId: JOB, workerId: WORKER, ...sectionBody('rooms') },
      }), deps as never);
      expect(res.status).toBe(401);
    }
    expect(db.rows('wv_room')).toHaveLength(0);
  });

  it('refuses a build assembled for a different property', async () => {
    const { db, deps } = rig();
    const res = await send(deps, { ...sectionBody('header'), propertyId: PROP_B });
    expect(res.status).toBe(422);
    expect((res.body as { error: string }).error).toContain('different property');
    expect(db.rows('wv_world').find((w) => w['id'] === WORLD_A)!['scale_source'])
      .toBeUndefined();
  });
});

// ---------------------------------------------------------------------------
// Malformed input
// ---------------------------------------------------------------------------

describe('a malformed world', () => {
  it('is refused before any of it reaches a table', async () => {
    const { db, deps } = rig();
    await send(deps, sectionBody('header'));
    await send(deps, sectionBody('floors'));

    const rooms = sectionBody('rooms');
    const rows = (rooms['rows'] as Record<string, unknown>[]).map((r) => ({ ...r }));
    rows[1]!['kind'] = 'dungeon';
    const res = await send(deps, { ...rooms, rows });

    expect(res.status).toBe(400);
    expect((res.body as { error: string }).error).toContain('not a known room kind');
    // Not one row, not even the good one that preceded it.
    expect(db.rows('wv_room')).toHaveLength(0);
  });

  it('refuses a scale that claims to have been observed', async () => {
    const { deps } = rig();
    const header = sectionBody('header');
    const scale = { ...(header['scale'] as Record<string, unknown>) };
    scale['grounding'] = { provenance: 'observed', confidence: 0.99 };
    const res = await send(deps, { ...header, scale });
    expect(res.status).toBe(400);
    expect((res.body as { error: string }).error).toContain('cannot be `observed`');
  });

  it('refuses an entity no camera saw that claims to have been observed', async () => {
    const { db, deps } = rig();
    for (const name of ['header', 'floors', 'rooms', 'surfaces', 'openings', 'cameras']) {
      await send(deps, sectionBody(name));
    }
    const entities = sectionBody('entities');
    const rows = (entities['rows'] as Record<string, unknown>[]).map((r) => ({ ...r }));
    rows[0]!['observedIn'] = [];
    rows[0]!['grounding'] = { provenance: 'reconstructed', confidence: 0.9 };
    const res = await send(deps, { ...entities, rows });
    expect(res.status).toBe(400);
    expect((res.body as { error: string }).error).toContain('no observing camera');
    expect(db.rows('wv_entity')).toHaveLength(0);
  });

  it('refuses to let a worker claim the chunk key readers trust', async () => {
    const { deps } = rig();
    const res = await send(deps, {
      section: 'assets', chunkIndex: 0, chunkCount: 1,
      rows: [{ name: 'evil.json', role: 'export_bundle', format: 'json',
        chunkKey: DOCUMENT_CHUNK_KEY }],
    });
    expect(res.status).toBe(400);
    expect((res.body as { error: string }).error).toContain('reserved');
  });
});

// ---------------------------------------------------------------------------
// The cached document
// ---------------------------------------------------------------------------

describe('the rendered document', () => {
  it('is served from storage until a correction invalidates it', async () => {
    const { db, deps, storage } = rig();
    await handOff(deps);

    const first = await readWorldDocument(deps, WORLD_A);
    expect(first.fromCache).toBe(true);
    const downloads = storage.objects.size;

    // An operator renames a room. The write lands in the row -- which is the
    // whole point of the rows being the world -- and the cached rendering is
    // no longer what the world says.
    const room = db.rows('wv_room')[0]!;
    await db.update('wv_room', { name: 'Front reception' }, { id: String(room['id']) });
    expect(await markWorldDocumentStale(deps, WORLD_A, 'operator correction')).toBe(true);

    const second = await readWorldDocument(deps, WORLD_A);
    expect(second.fromCache).toBe(false);
    const names = (second.document['rooms'] as { name?: string }[]).map((r) => r.name);
    expect(names).toContain('Front reception');
    expect(storage.objects.size).toBe(downloads);   // replaced, not accumulated

    // And it is cached again, so the next reader pays nothing.
    expect((await readWorldDocument(deps, WORLD_A)).fromCache).toBe(true);
  });

  it('re-renders rather than serving a cached file it cannot read', async () => {
    const { deps, storage, logs } = rig();
    await handOff(deps);
    storage.objects.set(`${ASSET_BUCKET}/${WORLD_A}/world.json`, utf8('{ truncated'));

    const out = await readWorldDocument(deps, WORLD_A);
    expect(out.fromCache).toBe(false);
    expect((out.document['rooms'] as unknown[]).length)
      .toBe((FIXTURE.document['rooms'] as unknown[]).length);
    expect(logs.some((l) => l.event === 'wv_document_cache_unusable')).toBe(true);
  });

  it('reports nothing to invalidate for a world that was never published', async () => {
    const { deps } = rig();
    expect(await markWorldDocumentStale(deps, WORLD_A, 'nothing yet')).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// What the worker is told when it claims
// ---------------------------------------------------------------------------

describe('claim', () => {
  it('hands the worker the world\'s own identity', async () => {
    const { db, deps } = rig();
    db.rows('wv_job')[0]!['status'] = 'queued';
    db.rows('wv_job')[0]!['worker_id'] = null;
    db.setRpc('wv_claim_job', (args) => {
      const job = db.rows('wv_job')[0]!;
      job['status'] = 'leased';
      job['worker_id'] = args['p_worker_id'];
      return [{ ...job }];
    });

    const res = await handleJobs(req({
      headers: { 'x-wv-worker-secret': SECRET },
      body: { action: 'claim', workerId: WORKER, stages: ['quality'] },
    }), deps as never);

    expect(res.status).toBe(200);
    // The pod must not have to guess whose property this is: a document
    // stamped with a property id it chose would disagree with the database
    // and the ingest would refuse every build.
    const world = (res.body as { job: { world: Record<string, unknown> } }).job.world;
    expect(world['propertyId']).toBe(PROP_A);
    expect(world['version']).toBe(FIXTURE.version);
    expect(world['label']).toBe(FIXTURE.label);
    expect(world['slug']).toBe('flat-2-alpha-court');
  });
});
